# Generated by Django 3.1 on 2020-08-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
